### ISSUE TITLE
Fix ref on GenericEnvironment.GetEnvironmentVariable in ReadMe

### ISSUE THREAD

**Issue by kurnakovv** [kurnakovv/GenericEnvironment#20]
Fix [this line](https://github.com/kurnakovv/GenericEnvironment/blob/main/ReadMe.md?plain=1#L56)
From `DocsReadMe.md#GenericEnvironment.GetEnvironmentVariable` to `DocsReadMe.md#genericenvironmentgetenvironmentvariable`

**Comment by vizerion07** [comment]
I'd like to work on this! Please assign me this issue

**Comment by kurnakovv** [comment]
@vizerion07 ok, good luck ;)
If you need some help, you can ask, no problem

**Comment by kurnakovv** [comment]
This task completed in this PR https://github.com/kurnakovv/GenericEnvironment/pull/22
